# Updated harness-delegate.yml

# This file configures the AWS IAM Authenticator installation using an init container.

apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
    - name: my-app-container
      image: my-app-image
      # Your container configuration here
  initContainers:
    - name: install-aws-iam-authenticator
      image: amazonlinux
      command: ['sh', '-c', 'yum install -y aws-iam-authenticator']
      volumeMounts:
        - name: aws-iam-authenticator
          mountPath: /usr/local/bin
  volumes:
    - name: aws-iam-authenticator
      emptyDir: {}
