apiVersion: v1
kind: Namespace
metadata:
  name: harness-delegate

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: harness-delegate
  namespace: harness-delegate

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: harness-delegate-cluster-role
rules:
# Core API group
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
# Apps API group
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
# Extensions API group
- apiGroups: ["extensions"]
  resources: ["*"]
  verbs: ["*"]
# Batch API group
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["*"]
# RBAC API group
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
# Networking API group
- apiGroups: ["networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
# Storage API group
- apiGroups: ["storage.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
# All other API groups
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: harness-delegate-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: harness-delegate
  namespace: harness-delegate
roleRef:
  kind: ClusterRole
  name: harness-delegate-cluster-role
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: Secret
metadata:
  name: kubernetes-delegate-account-token
  namespace: harness-delegate
type: Opaque
data:
  DELEGATE_TOKEN: "Nzg3Y2RmNmFkMGY1YmZjZGJjMTBmYzY2MjFlZTM4MzE="

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: release-b88c50
  namespace: harness-delegate
data:
  config: |
    release.name=release-b88c50

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    harness.io/name: kubernetes-delegate
  name: kubernetes-delegate
  namespace: harness-delegate
spec:
  replicas: 1
  selector:
    matchLabels:
      harness.io/name: kubernetes-delegate
  template:
    metadata:
      labels:
        harness.io/name: kubernetes-delegate
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3460"
        prometheus.io/path: "/api/metrics"
    spec:
      terminationGracePeriodSeconds: 600
      restartPolicy: Always
      serviceAccountName: harness-delegate
      containers:
      - image: harness/delegate:23.10.81010
        imagePullPolicy: Always
        name: delegate
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "2048Mi"
          requests:
            cpu: "0.5"
            memory: "2048Mi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3460
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/health
            port: 3460
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 15
        envFrom:
        - secretRef:
            name: kubernetes-delegate-account-token
        env:
        - name: JAVA_OPTS
          value: "-Xms64M"
        - name: ACCOUNT_ID
          value: wGd7ZATCReysstwqqiWNZw
        - name: MANAGER_HOST_AND_PORT
          value: https://app.harness.io
        - name: DEPLOY_MODE
          value: KUBERNETES
        - name: DELEGATE_NAME
          value: kubernetes-delegate
        - name: DELEGATE_TYPE
          value: "KUBERNETES"
        - name: DELEGATE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INIT_SCRIPT
          value: |
            #!/bin/bash
            set -e
            
            echo "Starting AWS tools installation..."
            
            # Update and install required packages
            microdnf update -y && microdnf install -y curl unzip || true
            
            # Install aws-iam-authenticator
            echo "Installing aws-iam-authenticator..."
            curl -L -o /usr/local/bin/aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
            chmod +x /usr/local/bin/aws-iam-authenticator
            
            # Install AWS CLI v2
            echo "Installing AWS CLI v2..."
            cd /tmp
            curl -L "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -q awscliv2.zip
            ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli
            
            # Verify installations
            echo "Verifying installations..."
            aws-iam-authenticator version || echo "aws-iam-authenticator installation failed"
            aws --version || echo "aws cli installation failed"
            
            echo "AWS tools installation completed!"
        - name: DELEGATE_DESCRIPTION
          value: ""
        - name: DELEGATE_TAGS
          value: ""
        - name: NEXT_GEN
          value: "true"
        - name: CLIENT_TOOLS_DOWNLOAD_DISABLED
          value: "true"
        - name: DELEGATE_RESOURCE_THRESHOLD
          value: ""
        - name: DYNAMIC_REQUEST_HANDLING
          value: "false"

---

apiVersion: v1
kind: Service
metadata:
  name: delegate-service
  namespace: harness-delegate
spec:
  type: ClusterIP
  selector:
    harness.io/name: kubernetes-delegate
  ports:
  - port: 8080
    targetPort: 8080